
version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - dev
  api:
    build:
      context: .
      dockerfile: ../api.Dockerfile
    volumes: 
      - ../..:/app
    working_dir: /app
    networks:
      - dev
    depends_on: 
      - dynamodb
    environment:
      DYNAMODB_URL: http://dynamodb:8000
    command: ./tasks/api.sh
    ports:
      - 7000:7000
networks:
    dev:
