
version: '3'
services:
  dynamodb_local:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - local
  api:
    build:
      context: .
      dockerfile: ../api.Dockerfile
    volumes: 
      - ../..:/app
    working_dir: /app
    networks:
      - local
    depends_on: 
      - dynamodb_local
    environment:
      DYNAMODB_URL: http://dynamodb_local:8000
    command: ./tasks/api.sh
    ports:
      - 7000:7000
networks:
    local:
