
version: '3'
services:
  dynamodb_local:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - integration
  api:
    build:
      context: .
      dockerfile: ../api.Dockerfile
    volumes: 
      - ../..:/app
    working_dir: /app
    networks:
      - integration
    command: ./tasks/api.sh
    ports:
      - 7000:7000
networks:
    integration:
