version: '3'
services:
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    networks: 
      - integration
    environment:
      DYNAMODB_URL: http://dynamodb_local:8000
    command: ./tasks/integration.sh
  dynamodb_local:
    image: amazon/dynamodb-local
    networks:
      - integration
networks:
    integration: