version: '3'
services:
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    networks: 
      - integration
    depends_on: 
      - dynamodb
      - api
    environment:
      DYNAMODB_URL: http://dynamodb:8000
      API_URL: http://api:7000
    command: ./tasks/integration.sh
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes: 
      - ..:/app
    working_dir: /app
    networks:
      - integration
    depends_on: 
      - dynamodb
    environment:
      DYNAMODB_URL: http://dynamodb:8000
    command: ./tasks/api.sh
  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - integration
networks:
    integration:
