name: pipeline
on:
  push:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker-compose -f tasks/docker-compose.yml build build
          docker-compose -f tasks/docker-compose.yml run build
          docker-compose -f tasks/docker-compose.yml down
      - name: integration
        run: |
          docker-compose -f tasks/integration.docker-compose.yml build integration
          docker-compose -f tasks/integration.docker-compose.yml run integration
          docker-compose -f tasks/integration.docker-compose.yml down
      - name: deploy
        env:
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          CFN_STACK_NAME: Stack
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          docker-compose -f tasks/docker-compose.yml build deploy
          docker-compose -f tasks/docker-compose.yml run deploy
          docker-compose -f tasks/docker-compose.yml down
